import type { Metadata } from 'next';
import { IBM_Plex_Mono, IBM_Plex_Sans, Inter, Lora } from 'next/font/google';
import './globals.css';
import type { ReactNode } from 'react';
import { cn } from '@/shared/ui/services/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
});

// const sourceSerif4 = Source_Serif_4({
//   variable: "--font-source-serif-4",
//   subsets: ["latin"],
// })

// const sourceSans3 = Source_Sans_3({
//   variable: "--font-source-sans-3",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={cn('scroll-smooth', inter.variable)}>
      <body
        className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} ${lora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
